# Telegram Bot
# telegram_config_file: telegram_config.yml


# Dataset and Splits
data_root: DATA
dataset_class: dataset.GraphPropertyPrediction
dataset_name:  SSSP
data_splits_file:  DATA_SPLITS/SSSP/SSSP_outer1_inner1.splits


# Hardware
device:  cuda
max_cpus:  64
max_gpus: 4
gpus_per_task:  0.1
# gpus_subset: 0,1,2,3,4,5,6,7,8


# Data Loading
dataset_getter: pydgn.data.provider.DataProvider
data_loader:
  class_name: torch_geometric.loader.DataLoader
  args:
    num_workers : 1
    pin_memory: True

# Reproducibility
seed: 42


# Experiment
result_folder: UDN_RESULTS_300PATIENCE/ABLATION
exp_name: udn_gin
experiment: experiment.UDN_SupervisedExperiment
higher_results_are_better: False
evaluate_every: 1
final_training_runs: 20


grid:
  supervised_config:
    model: model_newfilter.AMP
    checkpoint: True
    shuffle: True
    batch_size: 512
    epochs: 1500

    # Model specific arguments #

    # treat the minibatch ELBO as if we had run an entire pass over the dataset
    # essentially it rescales the minibatch gradient of the classification term
    # therefore avoiding that other terms dominate the loss
    n_observations: 5120  # approx training set size

    filter_messages:
      - 'embedding-no-weight-sharing'
      - 'input_features'

    quantile: 0.99

    conv_layer: 'GINConv'

    hidden_dim:
      - 10
      - 20
      - 30

    layer_generator: layer_generator.DGNGenerator

    truncated_distribution:
      - class_name: distribution.FixedDepth
        args:
          depth: 2  # using 2 because layer 1 is a node embedding, different logic from ADGN paper's implementation of GIN method

    # scale for p(theta)
    theta_prior_scale:
      - 10.

    # p(ell)
    layer_prior:
      - null

    global_aggregation: false

    # ------------------------ #

    # Optimizer (with an example - 3 possible alternatives)
    optimizer:
      - class_name: optimizer.Optimizer
        args:
          optimizer_class_name: torch.optim.Adam
          lr:
            - 0.003
          weight_decay: 0.

    # Scheduler (optional)
    scheduler: null

    # Loss metric (with an example of Additive Loss)
    loss: metric.UDN_ELBO_Regression


    # Score metric (with an example of Multi Score)
    scorer:
      - class_name: pydgn.training.callback.metric.MultiScore
        args:
          main_scorer:
            - class_name: metric.GraphWiseLogMSE  # follow same metric computation of ADGN paper
              args:
                accumulate_over_epoch: False  # follow same metric computation of ADGN paper
          depth: metric.UDN_Depth
          UDN_WeightedLogLikelihood: metric.UDN_WeightedLogLikelihoodRegression
          UDN_theta_hidden: metric.UDN_theta_hidden
          UDN_theta_output: metric.UDN_theta_output
          UDN_entropy: metric.UDN_entropy
          UDN_prior_layer: metric.UDN_prior_layer

    # Readout (optional)
    readout: null

    # Training engine
    engine: pydgn.training.engine.TrainingEngine

    # Gradient clipper (optional)
    gradient_clipper: null

    # Early stopper (optional, with an example of "patience" early stopping on the validation score)
    early_stopper:
      - class_name:
          - pydgn.training.callback.early_stopping.PatienceEarlyStopper
        args:
          patience:
            - 300
          # SYNTAX: (train_,validation_)[name_of_the_scorer_or_loss_to_monitor] -> we can use MAIN_LOSS or MAIN_SCORE
          monitor: validation_main_score
          mode: min  # is best the `max` or the `min` value we are monitoring?
          checkpoint: True  # store the best checkpoint

    # Plotter of metrics
    plotter: plotter.StatsPlotter